<?php
/**
 * @file
 * Provides a UI for administering Commerce AvaTax.
 */

/**
 * Implements hook_menu().
 */
function commerce_tax_services_ui_menu() {
  $items = array();

  $items['admin/commerce/config/tax-services'] = array(
    'access arguments' => array('administer tax services'),
    'title' => 'Tax Services settings',
    'description' => 'Configure Tax Services',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_tax_services_ui_admin_settings'),
    'file' => 'includes/commerce_tax_services_ui.admin.inc',
  );

  return $items;
}
