<?php
/**
 * Created by PhpStorm.
 * User: BMcClure
 * Date: 3/16/2016
 * Time: 5:15 PM
 */

function commerce_tax_services_taxjar_tax_service_info() {
  $tax_services = array();

  $tax_services['taxjar'] = array(
    'name' => t('TaxJar'),
    'module' => 'commerce_tax_services_taxjar',
  );

  return $tax_services;
}

function commerce_tax_services_taxjar_tax_service_calculate($order, $variables) {

}

function commerce_tax_services_taxjar_tax_service_admin_options($form, $form_state) {
  $options = array();

  // TODO: Add custom fields for TaxJar options here

  return $options;
}
